# Generated by Django 5.1.2 on 2024-10-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_url",
                    models.FileField(
                        upload_to="documents", verbose_name="документ для загрузки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время загрузки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("document uploaded", "документ загружен"),
                            ("document confirmed", "документ подтвержден"),
                            ("document rejected", "документ отклонен"),
                        ],
                        default="document uploaded",
                        max_length=20,
                        verbose_name="статус документа",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "документы",
            },
        ),
    ]
