# Generated by Django 5.1.2 on 2024-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_rename_document_url_document_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                upload_to="documents", verbose_name="загруженный документ"
            ),
        ),
    ]
